-- Nuclear face reset: wipe all accumulated face data so the pipeline
-- can re-detect and re-cluster from scratch with the corrected quality
-- filters (pose/occlusion/quality gates, strict attribute requirement).
--
-- Safe to re-run: all deleted data is fully re-generated by the pipeline.

begin;

-- Remove all auto-labelled people rows (will be recreated by clusterPeople).
-- Manually labelled people (display_name set, auto_label null) are preserved.
delete from public.people
where auto_label is not null;

-- Clear face arrays from every asset_ai_enrichment row so enrichAI
-- re-detects faces with the corrected Rekognition call (DetectionAttributes ALL,
-- image resize, quality gate).
update public.asset_ai_enrichment
set faces = '[]'::jsonb
where faces is not null and faces != '[]'::jsonb;

-- Reset face_scanned_at so every asset is re-queued for enrichAI.
update public.assets
set face_scanned_at = null
where face_scanned_at is not null;

commit;

select
  (select count(*) from public.people where auto_label is null) as manual_people_preserved,
  (select count(*) from public.people) as total_people_after,
  (select count(*) from public.assets where face_scanned_at is null) as assets_queued_for_rescan;
